// SVG previews of block shapes, generated from the geometry that places them

import { Color } from "./color"
import { appendShape, type BlockShape } from "./grid/shapes"
import { FLOATS_PER_VERTEX, MeshBuilder } from "./mesh"

/**
 * A block's outline as SVG path data, in a `size` by `size` box.
 *
 * Generated by running appendShape rather than drawn by hand, so a thumbnail can
 * never disagree with the block it previews - add a shape to shapes.ts and its
 * preview appears, already correct. appendShape needs no GPU, which is what
 * makes this possible at all.
 *
 * One subpath per triangle. They overlap along shared edges, which an SVG fill
 * merges into a single silhouette.
 */
export function shapeSvgPath(
    shape: BlockShape,
    turns = 0,
    mirrored = false,
    size = 100,
): string {
    const builder = new MeshBuilder()
    // The color is irrelevant here; the SVG element supplies the fill
    appendShape(builder, shape, turns, mirrored, 0, 0, size, Color.WHITE)

    const data = builder.toArray()
    const parts: string[] = []

    // Two decimals: the arcs come out of cos/sin and full precision would triple
    // the string for sub-pixel detail nobody can see at thumbnail size
    const round = (value: number) => Number(value.toFixed(2))

    for (let i = 0; i + FLOATS_PER_VERTEX * 3 <= data.length; i += FLOATS_PER_VERTEX * 3) {
        const ax = round(data[i]!), ay = round(data[i + 1]!)
        const bx = round(data[i + 5]!), by = round(data[i + 6]!)
        const cx = round(data[i + 10]!), cy = round(data[i + 11]!)

        parts.push(`M${ax} ${ay}L${bx} ${by}L${cx} ${cy}Z`)
    }

    return parts.join("")
}